### ISSUE TITLE
ep-3 Which Datafile? 

### ISSUE THREAD

**Issue by kristi-sara** [UCSBCarpentry/2020-11-09-OpenRefine-online#3]
setup includes DOAJ_small and DOAJ_big. First lesson says download DOAJ_article_sample.csv.

**Comment by kristi-sara** [comment]
also under importing second dataset on episdoe 03 working with data,  "journalcsv__doaj_20201027_1636_utf8.csv file" isnt part of the set up. Part of me is assuming that Doaj small = doaj article sample and doaj big = this journal csv file?

**Comment by jonjab** [comment]
setup, ep. 2 and ep. 3 have been edited to reflect final versions of the files.
